name: Release
on: 
    push:
        tags: 'v*.*.*'
        
permissions:
    contents: write
    
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
              
            - name: Install dependencies
              run: sudo apt-get update && sudo apt-get install -y build-essential dpkg cmake g++
              
            - name: Configure
              run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF
              
            - name: Build
              run: cmake --build build --config Release
              
            - name: Package
              run: cmake --build build --target package
              
            - name: Create release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: ${{ github.ref_name }}
                files: build/*.deb
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
