name: RK
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            
            - name: Add GTests
              run: git clone https://github.com/google/googletest.git third-party/gtest
              
            - name: Install dependencies
              run: sudo apt-get update && sudo apt-get install -y build-essential cmake libgtest-dev googletest g++
              
            - name: Configure
              run: cmake -S . -B build -DBUILD_TESTS=ON
              
              
            - name: Build
              run: cmake --build build
              
            - name: Run tests
              run: build/test0

